<?php
header('Content-Type: application/json');
$data = '{
   "w": 1,
   "gms":    [
            {
         "hs": 7,
         "d": "Tue",
         "gsis": 56901,
         "vs": 3,
         "eid": 2016060800,
         "h": "DEN",
         "ga": "",
         "rz": -1,
         "v": "CAR",
         "vnn": "Panthers",
         "t": "6:00",
         "q": "1",
         "hnn": "Broncos"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56902,
         "vs": 0,
         "eid": 2016091100,
         "h": "ATL",
         "ga": "",
         "rz": -1,
         "v": "TB",
         "vnn": "Buccaneers",
         "t": "1:00",
         "q": "P",
         "hnn": "Falcons"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56903,
         "vs": 0,
         "eid": 2016091101,
         "h": "BAL",
         "ga": "",
         "rz": -1,
         "v": "BUF",
         "vnn": "Bills",
         "t": "1:00",
         "q": "P",
         "hnn": "Ravens"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56904,
         "vs": 0,
         "eid": 2016091102,
         "h": "HOU",
         "ga": "",
         "rz": -1,
         "v": "CHI",
         "vnn": "Bears",
         "t": "1:00",
         "q": "P",
         "hnn": "Texans"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56905,
         "vs": 0,
         "eid": 2016091103,
         "h": "JAX",
         "ga": "",
         "rz": -1,
         "v": "GB",
         "vnn": "Packers",
         "t": "1:00",
         "q": "P",
         "hnn": "Jaguars"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56906,
         "vs": 0,
         "eid": 2016091104,
         "h": "KC",
         "ga": "",
         "rz": -1,
         "v": "SD",
         "vnn": "Chargers",
         "t": "1:00",
         "q": "P",
         "hnn": "Chiefs"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56907,
         "vs": 0,
         "eid": 2016091105,
         "h": "NO",
         "ga": "",
         "rz": -1,
         "v": "OAK",
         "vnn": "Raiders",
         "t": "1:00",
         "q": "P",
         "hnn": "Saints"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56908,
         "vs": 0,
         "eid": 2016091106,
         "h": "NYJ",
         "ga": "",
         "rz": -1,
         "v": "CIN",
         "vnn": "Bengals",
         "t": "1:00",
         "q": "P",
         "hnn": "Jets"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56909,
         "vs": 0,
         "eid": 2016091107,
         "h": "PHI",
         "ga": "",
         "rz": -1,
         "v": "CLE",
         "vnn": "Browns",
         "t": "1:00",
         "q": "P",
         "hnn": "Eagles"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56910,
         "vs": 0,
         "eid": 2016091108,
         "h": "TEN",
         "ga": "",
         "rz": -1,
         "v": "MIN",
         "vnn": "Vikings",
         "t": "1:00",
         "q": "P",
         "hnn": "Titans"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56911,
         "vs": 0,
         "eid": 2016091109,
         "h": "SEA",
         "ga": "",
         "rz": -1,
         "v": "MIA",
         "vnn": "Dolphins",
         "t": "4:05",
         "q": "P",
         "hnn": "Seahawks"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56912,
         "vs": 0,
         "eid": 2016091110,
         "h": "DAL",
         "ga": "",
         "rz": -1,
         "v": "NYG",
         "vnn": "Giants",
         "t": "4:25",
         "q": "P",
         "hnn": "Cowboys"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56913,
         "vs": 0,
         "eid": 2016091111,
         "h": "IND",
         "ga": "",
         "rz": -1,
         "v": "DET",
         "vnn": "Lions",
         "t": "4:25",
         "q": "P",
         "hnn": "Colts"
      },
            {
         "hs": 0,
         "d": "Sun",
         "gsis": 56914,
         "vs": 0,
         "eid": 2016091112,
         "h": "ARI",
         "ga": "",
         "rz": -1,
         "v": "NE",
         "vnn": "Patriots",
         "t": "8:30",
         "q": "P",
         "hnn": "Cardinals"
      },
            {
         "hs": 0,
         "d": "Mon",
         "gsis": 56915,
         "vs": 0,
         "eid": 2016091200,
         "h": "WAS",
         "ga": "",
         "rz": -1,
         "v": "PIT",
         "vnn": "Steelers",
         "t": "7:10",
         "q": "P",
         "hnn": "Redskins"
      },
            {
         "hs": 0,
         "d": "Mon",
         "gsis": 56916,
         "vs": 0,
         "eid": 2016091201,
         "h": "SF",
         "ga": "",
         "rz": -1,
         "v": "LA",
         "vnn": "Rams",
         "t": "10:20",
         "q": "P",
         "hnn": "49ers"
      }
   ],
   "t": "REG",
   "gd": "0",
   "bph": "0",
   "y": 2016
}';
echo ($data);